### ISSUE TITLE
🗑️ Remover Campo `Categorias` de Questões e Painel Administrativo

### ISSUE THREAD

**Issue by eduesplinio** [teste-de-progresso/progress-test#21]
Campo `Categorias` removido na branch [remove-question-category-field](https://github.com/teste-de-progresso/progress-test/tree/remove-question-category-field)

![Image](https://github.com/teste-de-progresso/progress-test/assets/63748745/f9e3cfc3-3c3d-4dc6-becb-8a24474e0f3f)

**Comment by otavioms** [comment]
Também foi necessário remover o campo `Categoria` do painel administrativo e também ajustar as consultas para serem feitas sem está informação, e com isso foi ajustado para não haver mais a criação da tabela categoria no banco de dados.
Todas as alterações foram feitas na branch [fix/remove-campo-categoria](https://github.com/teste-de-progresso/progress-test/tree/fix/remove-campo-categoria).


![Image](https://github.com/teste-de-progresso/progress-test/assets/121903776/7ec0c085-5324-4453-8eda-8197bc7acb69)
